### ISSUE TITLE
Some reasonable branch structure

### ISSUE THREAD

**Issue by dexX7** [mastercoin-MSC/mastercore#130] opened 2014-09-16 21:46 UTC
Is there a chance to adopt a branch structure which is more telling? Something like master (latest stable?), developement, one for each release whereby those are prefixed or something to differentiate between Bitcoin and Master releases. Sort of confusing to see 0.0.7, 0.6.2, 0.9.1 etc. ;) ...

Which one is the "active dev" branch at the moment?

**Comment by m21** [comment] 2014-09-16 21:52
Active dev is now : https://github.com/mastercoin-MSC/mastercore/tree/mscore-0.0.8
0.0.7 is the tip default (frozen to the 0.0.7 tag)
Prefix is a good idea, what do you suggest?

UPDATED to the new branch name

**Comment by dexX7** [comment] 2014-09-16 21:58
Hmm.. given there is actually quite some space, if it's just the release number, you might as well use bitcoin- and mastercore- or so, not sure. ;)

Since there is no way (that I was able to get to work) to maintain two repos forked from the same project, my address indexed branch is mixed with Mastercoin stuff and I use `0.9.1-addrindex-extended` and `mcore-swap-sendrawtx-arguments`, `mcore-fix-listblocktxs-crash` etc., prefixing with mcore, but I'd say: it doesn't matter as long as there is a differentiation.

**Comment by ghost** [comment] 2014-09-16 22:07
Dexx, you can maintain two repos forked from the same project by adding two separate remotes

git remote add bitcoin git@github.com:bitcoin/bitcoin.git
git remote add mscore git@github.com:mastercoin-MSC/mastercore.git

thats what i use, I hope it helps

**Comment by dexX7** [comment] 2014-09-16 22:42
Ah, thanks, I'm not sure, if this is what I intend.

If you head over to https://github.com/bitcoin/bitcoin and click on "fork", you'll probably be redirected to your mastercore fork.

More than one remote is no problem, but the best what I was able to do was to create mastercore as "new" project, but going this route won't show the "forked from xxx" line, so I decided to just use "bitcoin" and use prefixes for feature branches.

**Comment by msgilligan** [comment] 2014-09-16 23:31
I recommend using (a slightly simplified version of) the branching model described in the well-known article [A successful Git branching model](http://nvie.com/posts/a-successful-git-branching-model/)

I've used this on several projects with small to medium sized teams and it has worked well.

Since `master` is taken by upstream, I would recommend `msc-master` and `msc-dev`

**Comment by m21** [comment] 2014-09-16 23:45
Ok, the latest & greatest dev branch is now: https://github.com/mastercoin-MSC/mastercore/tree/mscore-0.0.8
 guys note @zathras-crypto @faizkhan00 

@dexX7 does that give you enough differentiation?

**Comment by dexX7** [comment] 2014-09-16 23:59
Actually I think this might create the impression 0.0.8 is already a stable release and not in developement.

Something like `-dev` or `-development` seems much more explicit and not bound to a specific version, but can always be used as "the latest active dev branch".

I'd also delete all < 0.9 Bitcoin branches and the unused ones in general. Those are: `michael, develop, new_m13, commenting_m6, inital, 0.8.6, 0.8.5, 0.8.4, 0.8.3, 0.8.1, 0.7.2, 0.6.3, 0.6.2, blockheaders, freenode-verf`.

I'm not sure, if this is best-practise or side-effect free, but seems cleaner.

**Comment by m21** [comment] 2014-09-17 00:02
Well 0.9.3 is not out :)

https://github.com/bitcoin/bitcoin/tree/0.9.3

UPDATE: agreed about deleting obsolete branches.

**Comment by ghost** [comment] 2014-09-17 00:04
Agreed on branches, disagree on -dev

All official feature releases are tagged, so if its not a tag, the rule is that its in development or even experimental.

edit: I accidentally a word

**Comment by dexX7** [comment] 2014-09-17 00:08
Ah, I see your point, but the main branch is `master` and `0.9.3` was derived from there.

@faizkhan00: do you suggest to use `0.0.8` and after the release create `0.0.9` as new "active branch"?

**Comment by msgilligan** [comment] 2014-09-17 00:14
If you haven't already, please take a look at the article I linked. It is an excellent article and it is widely followed - including (more or less) by upstream, I believe.

From upstream:
"The master branch is regularly built and tested, but is not guaranteed to be completely stable." [link](https://github.com/bitcoin/bitcoin#development-process)

Since `master` is used by upstream, we should use something like `msc-master`. Perhaps it is overkill to have a `msc-develop` at this point. In any event, there should be an ongoing, current branch that does not have a version number in it -- the version numbered branches are then spun off at the appropriate times.

**Comment by ghost** [comment] 2014-09-17 00:18
@dexX7 Sure, I don't see why we would deviate from that convention

There is a good reason for this, mainly due to featureset but also because of the code involved.

If a fix goes out to 0.0.7, we won't commit this to -develop but to 0.0.7.1, because the changes cannot (or should not) be applied to a later branch. Separation by release also allows for easier tagging, by which one can do within the UI by branch. This kind of technique can be seen being used by the Core Developers (see 0.9.2 and 0.9.2.1 as the hotfix branch) and as such I see it as noncontroversial.

Note: Bitcoin Core's 'master' is pretty cutting edge (already including many features slated for 0.10, including the bitcoin-tx tool, watch addresses, among other things) and its yet to be seen if there's really any benefit in doing that this early in the codebase's lifecycle, between tags, where there might be one (or several) regressions.

**Comment by dexX7** [comment] 2014-09-17 00:21
@msgilligan: the model which you linked doesn't consider `master` as unstable branch, but:

> We consider origin/master to be the main branch where the source code of HEAD always reflects a **production-ready** state.
> We consider origin/develop to be the main branch where the source code of HEAD always reflects a state with the latest delivered development changes ...

http://nvie.com/posts/a-successful-git-branching-model/ (indeed good read btw.)

This is not the case with bitcoin's `master` which is rather experimental.

Edit: maybe it is considered as production-ready and [bitcoin#development-process](https://github.com/bitcoin/bitcoin#development-process) somehow hints this with "Developers work in their own trees, ...".

Edit: either way, as long as there is some structure which is explicit and overall consistent, I'm fine. ;)

**Comment by msgilligan** [comment] 2014-09-17 00:28
Yeah, bitcoin's master seems to be a combination of the `master` and `develop` branches from the "Successful" model. I like the idea of having an ongoing stable branch and an ongoing stable-ish integration/develop branch, but that does add a little complexity. That's why I'm backing away from advocating a `msc-develop` and suggesting we just start with simply `msc-master`.  (`msc-develop` can be added when there is a documented/requested need for it.)

(Note that in some continuous deployment scenarios the `master` branch gets automatically deployed to a staging or even production server, that's why they need the `develop` branch as well.)

**Comment by msgilligan** [comment] 2014-09-17 16:28
A branch structure that uses named, long-lived branches makes Jenkins more useful (or at least easier to maintain) Jenkins can be triggered automatically from commits (or by clicking "Build now") and is generally configured for one or more specific branches.

So, obviously, you want Jenkins to test the master branch, but it's also useful to run Jenkins on a less stable, development, or integration branch. So if there's a `develop` branch, anytime something is merged onto that branch it will get tested.

**Comment by m21** [comment] 2014-09-21 02:18
Obsolete branches & BTC tags are deleted.

**Closed as completed by m21** 2014-09-21 02:18 UTC
